package.path = "./?.lua;./?/init.lua;" .. package.path

local tests = {
    "tests.test_json",
    "tests.test_modes",
    "tests.test_sandbox",
    "tests.test_topology",
    "tests.test_operator_registry",
    "tests.test_pressure",
    "tests.test_pressure_ablation",
    "tests.test_runtime_camera",
    "tests.test_tree_router",
    "tests.test_edge_evidence",
    "tests.test_edge_metric_roles",
    "tests.test_packet",
    "tests.test_field",
    "tests.test_connect",
    "tests.test_dissolve",
    "tests.test_finality",
    "tests.test_packet_memory",
    "tests.test_session_memory",
    "tests.test_budget",
    "tests.test_loss_accumulation",
    "tests.test_grave",
    "tests.test_substrates",
    "tests.test_tools",
    "tests.test_fs_tool",
    "tests.test_spells",
    "tests.test_freshness",
    "tests.test_trace_validator",
    "tests.test_encode",
    "tests.test_choose",
    "tests.test_cycle",
    "tests.test_foundation",
    "tests.test_body",
    "tests.test_observe",
    "tests.test_organs_encode_choose",
    "tests.test_manifest",
    "tests.test_operator_hints",
    "tests.test_repo_selection",
    "tests.test_runner",
    "tests.test_router",
    "tests.test_shadow_router",
    "tests.test_tree_authority",
    "tests.test_tree_instrumentation",
    "tests.test_tree_manifest_honesty",
    "tests.test_tension_runner",
    "tests.test_build_mode_lower_triangle",
}

for _, name in ipairs(tests) do
    require(name)
end

print("all tests ok")
