local catalog = {
    contract = {
        {"QC01", "plan birth has no executable QA contract"},
        {"QC02", "build policy binds exactly once at birth"},
        {"QC03", "software.create build receives the exact stage contract"},
        {"QC04", "same-stage recovery preserves contract identity"},
        {"QC05", "different stage cannot reuse current contract authority"},
        {"QC06", "substrate contract-shaped output has zero authority"},
        {"QC07", "invalid check count argv environment and stdin are rejected"},
        {"QC08", "one normalized field change changes identity"},
        {"QC09", "detached mutation changes no stored projection"},
        {"QC10", "unavailable old environment blocks instead of upgrading"},
        {"QC11", "missing exact sealed entrypoint calls no provider"},
        {"QC12", "foreign seal stage lineage or environment is not ready"},
        {"QC13", "public environment and profile ids grant no lease"},
        {"QC14", "environment availability requires exercised features"},
        {"QC15", "accepted output wording has zero verdict authority"},
    },
    execution = {
        {"QE01", "QA-disabled ablation has zero mass"},
        {"QE02", "public request has no command-shaped surface"},
        {"QE03", "public ids grant zero private authority"},
        {"QE04", "unsealed diverged or foreign candidate calls no provider"},
        {"QE05", "exact body request event precedes grant begin"},
        {"QE06", "source lease exposes no path fd or userdata"},
        {"QE07", "source root remains sealed and write-closed"},
        {"QE08", "request and lease replay launches no second supervisor"},
        {"QE09", "failed first attempt releases no authority"},
        {"QE10", "pre and post inventory reuse exact seal normalization"},
        {"QE11", "source drift writes no candidate outcome"},
        {"QE12", "candidate rejection and infrastructure failure stay distinct"},
        {"QE13", "malformed trusted report is loud"},
        {"QE14", "receipt body split is loud and never rerun"},
        {"QE15", "clean candidate outcome charges once"},
        {"QE16", "pre-dispatch denial charges no candidate process"},
        {"QE17", "foreign private coordinates are denied"},
        {"QE18", "detached mutation changes no private state"},
        {"QE19", "foreign lineage root alias grants no QA authority"},
        {"QE20", "repeated hostile lives leave no host residue"},
    },
    verdict = {
        {"QV01", "caller provider table has zero body authority"},
        {"QV02", "accepted report writes one accepted check"},
        {"QV03", "rejected report writes one rejected check"},
        {"QV04", "provider error writes one execution failure and no check"},
        {"QV05", "malformed trusted result is loud not mortality"},
        {"QV06", "foreign or stale coordinates cannot advance"},
        {"QV07", "alignment change before append writes no outcome"},
        {"QV08", "missing or contradictory private receipt is loud"},
        {"QV09", "accepted check before verdict derives build crystall"},
        {"QV10", "rejected check before verdict derives build crystall"},
        {"QV11", "exact accepted set derives accepted verdict and boundary"},
        {"QV12", "exact rejected set derives rejected verdict and boundary"},
        {"QV13", "execution failure yields no verdict and effect failure"},
        {"QV14", "conflicting accepted and rejected evidence is loud"},
        {"QV15", "exact replay writes and charges nothing twice"},
        {"QV16", "substrate wording changes no QA evidence"},
        {"QV17", "Packet accepted verdict is not lineage acceptance"},
        {"QV18", "rejected verdict before terminal cannot birth recovery"},
        {"QV19", "QA evidence survives trace tail truncation"},
        {"QV20", "ancestor QA remains historical in descendant"},
        {"QV21", "contained timeout differs from cleanup ambiguity"},
        {"QV22", "detached check and verdict mutation changes no trace"},
        {"QV23", "verdict assembly does not charge execution twice"},
        {"QV24", "accepted rendering stays below universal correctness"},
    },
    native = {
        {"QN01", "hostile fixture corpus is inert and complete"},
        {"QN02", "wire frame constants are exact and bounded"},
        {"QN03", "malformed wire frames fail closed"},
        {"QN04", "shared repository handle ABI is exact"},
        {"QN05", "launcher Lua ABI is closed"},
        {"QN06", "supervisor is exact static PIE"},
        {"QN07", "opened supervisor digest and ABI are verified"},
        {"QN08", "fork child crosses execveat memory erasure boundary"},
        {"QN09", "descriptor contract is fixed and closed"},
        {"QN10", "namespace creation is fail-closed"},
        {"QN11", "source mount is exact read-only noexec"},
        {"QN12", "candidate Lua state ignores host authority"},
        {"QN13", "seccomp denies process network and native escape"},
        {"QN14", "resource output and scratch limits are enforced"},
        {"QN15", "environment probe exercises the production path"},
        {"QN16", "clean and nonzero fixtures classify exactly"},
        {"QN17", "hostile candidate fixtures remain contained"},
        {"QN18", "trusted crashes and pipe faults remain infrastructure"},
        {"QN19", "cleanup ambiguity never becomes candidate rejection"},
        {"QN20", "repeated transactions leave no host residue"},
    },
}

return catalog
